name: Build and Deploy Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pantomimegame-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pantomimegame-frontend:buildcache,mode=max
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pantomimegame-frontend:${{ github.ref_name }}